// data.js
export const categories = [
  { id: "essentials", name: "Essentials" },
  { id: "phones", name: "Phones" },
  { id: "currencies", name: "Currencies" },
  { id: "fuel", name: "Fuel" },
  { id: "metals", name: "Metals" },
];

export const items = [
  // Essentials
  {
    id: 1,
    name: "Rice (1kg)",
    price: 1.22,
    change: 0.8,
    category: "essentials",
    image: "/products/rice.jpg",
  },
  {
    id: 2,
    name: "Beans (1kg)",
    price: 1.78,
    change: 0.0,
    category: "essentials",
    image: "/products/beans.jpg",
  },
  {
    id: 3,
    name: "Sugar (1kg)",
    price: 0.98,
    change: -0.1,
    category: "essentials",
    image: "/products/sugar.jpg",
  },
  {
    id: 4,
    name: "Flour (1kg)",
    price: 0.74,
    change: -0.6,
    category: "essentials",
    image: "/products/rice.jpg",
  },
  {
    id: 5,
    name: "Cooking Oil (1L)",
    price: 1.95,
    change: 0.0,
    category: "essentials",
    image: "/products/sugar.svg",
  },
  {
    id: 6,
    name: "Eggs (12 pack)",
    price: 2.35,
    change: 1.4,
    category: "essentials",
    image: "/products/beans.svg",
  },
  {
    id: 7,
    name: "Milk (1L)",
    price: 0.92,
    change: -0.3,
    category: "essentials",
    image: "/products/rice.svg",
  },
  {
    id: 8,
    name: "Black Tea (500g)",
    price: 3.4,
    change: 0.5,
    category: "essentials",
    image: "/products/sugar.svg",
  },

  // Phones (used)
  {
    id: 9,
    name: "iPhone 16 Pro Max (Used)",
    price: 905,
    change: -1.2,
    category: "phones",
    image: "/products/iphone-16-pro-max.svg",
  },
  {
    id: 10,
    name: "iPhone 15 Pro (Used)",
    price: 690,
    change: -0.8,
    category: "phones",
    image: "/products/iphone-15-pro.svg",
  },
  {
    id: 11,
    name: "Samsung S24 Ultra (Used)",
    price: 760,
    change: 0.6,
    category: "phones",
    image: "/products/iphone-16-pro-max.svg",
  },
  {
    id: 12,
    name: "Google Pixel 8 Pro (Used)",
    price: 540,
    change: -1.5,
    category: "phones",
    image: "/products/iphone-15-pro.svg",
  },
  {
    id: 13,
    name: "Xiaomi 14T (Used)",
    price: 410,
    change: 0.0,
    category: "phones",
    image: "/products/iphone-15-pro.svg",
  },
  {
    id: 14,
    name: "Tecno Camon 30 (Used)",
    price: 240,
    change: 1.8,
    category: "phones",
    image: "/products/iphone-16-pro-max.svg",
  },

  // Currencies (against AFN)
  {
    id: 15,
    name: "USD/AFN",
    price: 87.1,
    change: 0.45,
    category: "currencies",
    image: "/products/usd-afn.svg",
  },
  {
    id: 16,
    name: "EUR/AFN",
    price: 94.3,
    change: -0.12,
    category: "currencies",
    image: "/products/eur-afn.svg",
  },
  {
    id: 17,
    name: "GBP/AFN",
    price: 110.8,
    change: 0.22,
    category: "currencies",
    image: "/products/usd-afn.svg",
  },
  {
    id: 18,
    name: "AED/AFN",
    price: 23.71,
    change: -0.08,
    category: "currencies",
    image: "/products/eur-afn.svg",
  },
  {
    id: 19,
    name: "PKR/AFN",
    price: 0.31,
    change: 0.0,
    category: "currencies",
    image: "/products/usd-afn.svg",
  },
  {
    id: 20,
    name: "IRR/AFN",
    price: 0.0021,
    change: -0.5,
    category: "currencies",
    image: "/products/eur-afn.svg",
  },

  // Fuel
  {
    id: 21,
    name: "Petrol (per liter)",
    price: 0.87,
    change: 1.1,
    category: "fuel",
    image: "/products/petrol.svg",
  },
  {
    id: 22,
    name: "Liquid Gas (per kg)",
    price: 1.08,
    change: 0.0,
    category: "fuel",
    image: "/products/liquid-gas.svg",
  },
  {
    id: 23,
    name: "Diesel (per liter)",
    price: 0.84,
    change: -0.7,
    category: "fuel",
    image: "/products/petrol.svg",
  },
  {
    id: 24,
    name: "Kerosene (per liter)",
    price: 0.79,
    change: 0.4,
    category: "fuel",
    image: "/products/liquid-gas.svg",
  },
  {
    id: 25,
    name: "CNG (per m3)",
    price: 0.56,
    change: -0.2,
    category: "fuel",
    image: "/products/petrol.svg",
  },

  // Metals
  {
    id: 26,
    name: "Gold 24K (per gram)",
    price: 72.4,
    change: 1.7,
    category: "metals",
    image: "/globe.svg",
  },
  {
    id: 27,
    name: "Silver (per gram)",
    price: 0.91,
    change: -0.4,
    category: "metals",
    image: "/globe.svg",
  },
  {
    id: 28,
    name: "Copper (per kg)",
    price: 8.55,
    change: 0.3,
    category: "metals",
    image: "/globe.svg",
  },
  {
    id: 29,
    name: "Iron (per kg)",
    price: 0.62,
    change: 0.0,
    category: "metals",
    image: "/globe.svg",
  },
  {
    id: 30,
    name: "Aluminum (per kg)",
    price: 2.31,
    change: -0.9,
    category: "metals",
    image: "/globe.svg",
  },
];
