// data.js

// Helper function to generate price history
const generatePriceHistory = (currentPrice, volatility = 0.05) => {
  const history = [];
  let price = currentPrice;

  for (let i = 30; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    const change = price * (Math.random() * volatility * 2 - volatility);
    price = i === 0 ? currentPrice : price + change;
    history.push({
      date: date.toISOString().split("T")[0],
      price: Math.round(price * 100) / 100,
    });
  }

  return history;
};

export const categories = [
  { id: "essentials", name: "Essentials" },
  { id: "phones", name: "Phones" },
  { id: "currencies", name: "Currencies" },
  { id: "fuel", name: "Fuel" },
  { id: "metals", name: "Metals" },
];

export const sources = {
  baghQazi: { id: "bagh-qazi", name: "Bagh Qazi", shortName: "Bagh Qazi" },
  gulbahar: { id: "gulbahar", name: "Gulbahar Center", shortName: "Gulbahar" },
  saraiShahzada: { id: "sarai-shahzada", name: "Sarai Shahzada", shortName: "Sarai Shahzada" },
  localStation: { id: "local-station", name: "Kabul Fuel Stations", shortName: "Kabul Stations" },
  jewelry: { id: "jewelry", name: "Timur Shahi Market", shortName: "Timur Shahi" },
};

export const items = [
  // =====================
  // ESSENTIALS
  // =====================
  {
       id: 1,
    name: "Haji Aziz Rice",
    unit: "1 sack (24.5 kg)",
    price: 3800,
    change: 5,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/hajiaziz.jpg",
    description: "Premium quality Haji Aziz brand rice, perfect for daily cooking and special occasions.",
    priceHistory: generatePriceHistory(3800, 0.02),
    calculator: {
      baseQuantity: 24.5,
      displayUnit: "kg",
      step: 0.5,
      min: 0.5,
      presets: [
        { label: "1 kg", value: 1 },
        { label: "2 kg", value: 2 },
        { label: "½ ser", value: 3.5 },
        { label: "1 ser", value: 7 },
        { label: "2 ser", value: 14 },
        { label: "1 sack", value: 24.5 },
      ],
    },
    // ADD THIS - Unit price display options
    priceUnits: [
      { label: "1 kg", multiplier: 1 },
      { label: "1 ser (7 kg)", multiplier: 7 },
      { label: "1 sack (24.5 kg)", multiplier: 24.5 },
    ],
  },
  {
    id: 2,
    name: "Capsole Beans",
    unit: "1 ser (7 kg)",
    price: 750,
    change: 0,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/beans.jpg",
    description: "High-quality capsole beans, a staple in Afghan cuisine.",
    priceHistory: generatePriceHistory(750, 0.03),
    calculator: {
      baseQuantity: 7,
      displayUnit: "kg",
      step: 0.5,
      min: 0.5,
      presets: [
        { label: "1 kg", value: 1 },
        { label: "2 kg", value: 2 },
        { label: "½ ser", value: 3.5 },
        { label: "1 ser", value: 7 },
        { label: "2 ser", value: 14 },
        { label: "3 ser", value: 21 },
      ],
    },
    priceUnits: [
      { label: "1 kg", multiplier: 1 },
      { label: "1 ser (7 kg)", multiplier: 7 },
    ],
  },
  {
    id: 3,
    name: "Sugar",
    unit: "1 kg",
    price: 85,
    change: -3,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/sugar.jpg",
    description: "Refined white sugar for everyday use.",
    priceHistory: generatePriceHistory(85, 0.04),
    calculator: {
      baseQuantity: 1,
      displayUnit: "kg",
      step: 0.5,
      min: 0.5,
      presets: [
        { label: "½ kg", value: 0.5 },
        { label: "1 kg", value: 1 },
        { label: "2 kg", value: 2 },
        { label: "5 kg", value: 5 },
        { label: "1 ser", value: 7 },
        { label: "2 ser", value: 14 },
      ],
    },
    priceUnits: [
      { label: "1 kg", multiplier: 1 },
      { label: "1 ser (7 kg)", multiplier: 7 },
    ],
  },
  {
    id: 4,
    name: "Flour",
    unit: "1 kg",
    price: 65,
    change: -5,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/flour.jpg",
    description: "Fine wheat flour, ideal for bread and pastries.",
    priceHistory: generatePriceHistory(65, 0.03),
    calculator: {
      baseQuantity: 1,
      displayUnit: "kg",
      step: 0.5,
      min: 0.5,
      presets: [
        { label: "1 kg", value: 1 },
        { label: "2 kg", value: 2 },
        { label: "5 kg", value: 5 },
        { label: "1 ser", value: 7 },
        { label: "2 ser", value: 14 },
        { label: "50 kg", value: 50 },
      ],
    },
    priceUnits: [
      { label: "1 kg", multiplier: 1 },
      { label: "1 ser (7 kg)", multiplier: 7 },
      { label: "1 sack (50 kg)", multiplier: 50 },
    ],
  },
  {
    id: 5,
    name: "Cooking Oil",
    unit: "1 L",
    price: 170,
    change: 0,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/oil.jpg",
    description: "Vegetable cooking oil for all your culinary needs.",
    priceHistory: generatePriceHistory(170, 0.02),
    calculator: {
      baseQuantity: 1,
      displayUnit: "liter",
      step: 0.5,
      min: 0.5,
      presets: [
        { label: "½ L", value: 0.5 },
        { label: "1 L", value: 1 },
        { label: "2 L", value: 2 },
        { label: "5 L", value: 5 },
        { label: "10 L", value: 10 },
        { label: "16 L", value: 16 },
      ],
    },
    priceUnits: [
      { label: "1 liter", multiplier: 1 },
      { label: "5 liters", multiplier: 5 },
      { label: "16 liters (tin)", multiplier: 16 },
    ],
  },
  // Eggs, Milk, Tea - No priceUnits needed (single unit items)
  {
    id: 6,
    name: "Eggs",
    unit: "30 pack",
    price: 320,
    change: 15,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/eggs.jpg",
    description: "Farm fresh eggs, sold in packs of 30.",
    priceHistory: generatePriceHistory(320, 0.05),
    calculator: {
      baseQuantity: 1,
      displayUnit: "pack",
      step: 1,
      min: 1,
      presets: [
        { label: "1 pack", value: 1 },
        { label: "2 packs", value: 2 },
        { label: "3 packs", value: 3 },
        { label: "5 packs", value: 5 },
      ],
    },
    // No priceUnits - only sold by pack
  },
  {
    id: 7,
    name: "Milk",
    unit: "1 L",
    price: 80,
    change: -2,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/milk.jpg",
    description: "Fresh pasteurized milk.",
    priceHistory: generatePriceHistory(80, 0.03),
    calculator: {
      baseQuantity: 1,
      displayUnit: "liter",
      step: 0.5,
      min: 0.5,
      presets: [
        { label: "½ L", value: 0.5 },
        { label: "1 L", value: 1 },
        { label: "2 L", value: 2 },
        { label: "3 L", value: 3 },
        { label: "5 L", value: 5 },
      ],
    },
    // No priceUnits - simple per liter
  },
  {
    id: 8,
    name: "Black Tea",
    unit: "500g pack",
    price: 295,
    change: 10,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/tea.jpg",
    description: "Premium black tea leaves for traditional Afghan chai.",
    priceHistory: generatePriceHistory(295, 0.04),
    calculator: {
      baseQuantity: 1,
      displayUnit: "pack",
      step: 1,
      min: 1,
      presets: [
        { label: "1 pack", value: 1 },
        { label: "2 packs", value: 2 },
        { label: "3 packs", value: 3 },
        { label: "5 packs", value: 5 },
      ],
    },
  },

  // =====================
  // PHONES
  // =====================
  {
    id: 9,
    name: "iPhone 16 Pro Max",
    unit: "Used",
    price: 145000,
    change: -2000,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/iphone-16-pro-max.jpg",
    description: "Apple iPhone 16 Pro Max, used in good condition with all accessories.",
    priceHistory: generatePriceHistory(145000, 0.02),
    calculator: {
      baseQuantity: 1,
      displayUnit: "unit",
      step: 1,
      min: 1,
      presets: [{ label: "1 unit", value: 1 }],
    },
  },
  {
    id: 10,
    name: "iPhone 15 Pro",
    unit: "Used",
    price: 98000,
    change: -1500,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/iphone-15-pro.jpg",
    description: "Apple iPhone 15 Pro, used in excellent condition.",
    priceHistory: generatePriceHistory(98000, 0.03),
    calculator: {
      baseQuantity: 1,
      displayUnit: "unit",
      step: 1,
      min: 1,
      presets: [{ label: "1 unit", value: 1 }],
    },
  },
  {
    id: 11,
    name: "Samsung S24 Ultra",
    unit: "Used",
    price: 112000,
    change: 3000,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/samsung-s24.jpg",
    description: "Samsung Galaxy S24 Ultra, used with minor wear.",
    priceHistory: generatePriceHistory(112000, 0.025),
    calculator: {
      baseQuantity: 1,
      displayUnit: "unit",
      step: 1,
      min: 1,
      presets: [{ label: "1 unit", value: 1 }],
    },
  },
  {
    id: 12,
    name: "Google Pixel 8 Pro",
    unit: "Used",
    price: 78000,
    change: -2500,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/pixel-8.jpg",
    description: "Google Pixel 8 Pro, used in great condition.",
    priceHistory: generatePriceHistory(78000, 0.03),
    calculator: {
      baseQuantity: 1,
      displayUnit: "unit",
      step: 1,
      min: 1,
      presets: [{ label: "1 unit", value: 1 }],
    },
  },
  {
    id: 13,
    name: "Xiaomi 14T",
    unit: "Used",
    price: 52000,
    change: 0,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/xiaomi-14t.jpg",
    description: "Xiaomi 14T, used with original box.",
    priceHistory: generatePriceHistory(52000, 0.02),
    calculator: {
      baseQuantity: 1,
      displayUnit: "unit",
      step: 1,
      min: 1,
      presets: [{ label: "1 unit", value: 1 }],
    },
  },
  {
    id: 14,
    name: "Tecno Camon 30",
    unit: "Used",
    price: 28000,
    change: 1500,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/tecno-camon.jpg",
    description: "Tecno Camon 30, used in good working condition.",
    priceHistory: generatePriceHistory(28000, 0.04),
    calculator: {
      baseQuantity: 1,
      displayUnit: "unit",
      step: 1,
      min: 1,
      presets: [{ label: "1 unit", value: 1 }],
    },
  },

  // =====================
  // CURRENCIES
  // =====================
  {
    id: 15,
    name: "USD",
    unit: "1 USD",
    price: 70.5,
    change: 0.25,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/usd.jpg",
    description: "US Dollar exchange rate against Afghan Afghani.",
    priceHistory: generatePriceHistory(70.5, 0.01),
    calculator: {
      baseQuantity: 1,
      displayUnit: "USD",
      step: 1,
      min: 1,
      presets: [
        { label: "$10", value: 10 },
        { label: "$50", value: 50 },
        { label: "$100", value: 100 },
        { label: "$500", value: 500 },
        { label: "$1000", value: 1000 },
      ],
    },
  },
  {
    id: 16,
    name: "EUR",
    unit: "1 EUR",
    price: 76.2,
    change: -0.15,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/eur.jpg",
    description: "Euro exchange rate against Afghan Afghani.",
    priceHistory: generatePriceHistory(76.2, 0.015),
    calculator: {
      baseQuantity: 1,
      displayUnit: "EUR",
      step: 1,
      min: 1,
      presets: [
        { label: "€10", value: 10 },
        { label: "€50", value: 50 },
        { label: "€100", value: 100 },
        { label: "€500", value: 500 },
        { label: "€1000", value: 1000 },
      ],
    },
  },
  {
    id: 17,
    name: "GBP",
    unit: "1 GBP",
    price: 89.4,
    change: 0.35,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/gbp.jpg",
    description: "British Pound exchange rate against Afghan Afghani.",
    priceHistory: generatePriceHistory(89.4, 0.015),
    calculator: {
      baseQuantity: 1,
      displayUnit: "GBP",
      step: 1,
      min: 1,
      presets: [
        { label: "£10", value: 10 },
        { label: "£50", value: 50 },
        { label: "£100", value: 100 },
        { label: "£500", value: 500 },
        { label: "£1000", value: 1000 },
      ],
    },
  },
  {
    id: 18,
    name: "AED",
    unit: "1 AED",
    price: 19.2,
    change: -0.05,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/aed.jpg",
    description: "UAE Dirham exchange rate against Afghan Afghani.",
    priceHistory: generatePriceHistory(19.2, 0.01),
    calculator: {
      baseQuantity: 1,
      displayUnit: "AED",
      step: 1,
      min: 1,
      presets: [
        { label: "10 AED", value: 10 },
        { label: "50 AED", value: 50 },
        { label: "100 AED", value: 100 },
        { label: "500 AED", value: 500 },
        { label: "1000 AED", value: 1000 },
      ],
    },
  },
  {
    id: 19,
    name: "PKR",
    unit: "1000 PKR",
    price: 253,
    change: 0,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/pkr.jpg",
    description: "Pakistani Rupee exchange rate (per 1000 PKR) against Afghan Afghani.",
    priceHistory: generatePriceHistory(253, 0.02),
    calculator: {
      baseQuantity: 1, // Price is for 1 unit (= 1000 PKR)
      displayUnit: "× 1000 PKR",
      step: 1,
      min: 1,
      presets: [
        { label: "1K PKR", value: 1 },
        { label: "5K PKR", value: 5 },
        { label: "10K PKR", value: 10 },
        { label: "20K PKR", value: 20 },
        { label: "50K PKR", value: 50 },
      ],
    },
  },
  {
    id: 20,
    name: "IRR",
    unit: "100,000 IRR",
    price: 167,
    change: -2,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/irr.jpg",
    description: "Iranian Rial exchange rate (per 100,000 IRR) against Afghan Afghani.",
    priceHistory: generatePriceHistory(167, 0.03),
    calculator: {
      baseQuantity: 1,
      displayUnit: "× 100K IRR",
      step: 1,
      min: 1,
      presets: [
        { label: "100K IRR", value: 1 },
        { label: "500K IRR", value: 5 },
        { label: "1M IRR", value: 10 },
        { label: "2M IRR", value: 20 },
      ],
    },
  },

  // =====================
  // FUEL
  // =====================
  {
    id: 21,
    name: "Petrol",
    unit: "1 Liter",
    price: 58,
    change: 2,
    category: "fuel",
    source: sources.localStation,
    image: "/products/petrol.jpg",
    description: "Regular unleaded petrol price at Kabul fuel stations.",
    priceHistory: generatePriceHistory(58, 0.04),
    calculator: {
      baseQuantity: 1,
      displayUnit: "liter",
      step: 1,
      min: 1,
      presets: [
        { label: "5 L", value: 5 },
        { label: "10 L", value: 10 },
        { label: "20 L", value: 20 },
        { label: "30 L", value: 30 },
        { label: "50 L", value: 50 },
      ],
    },
  },
  {
    id: 22,
    name: "Liquid Gas",
    unit: "1 kg",
    price: 75,
    change: 0,
    category: "fuel",
    source: sources.localStation,
    image: "/products/lpg.jpg",
    description: "Liquefied Petroleum Gas (LPG) for household use.",
    priceHistory: generatePriceHistory(75, 0.03),
    calculator: {
      baseQuantity: 1,
      displayUnit: "kg",
      step: 1,
      min: 1,
      presets: [
        { label: "5 kg", value: 5 },
        { label: "10 kg", value: 10 },
        { label: "15 kg", value: 15 },
        { label: "20 kg", value: 20 },
        { label: "25 kg", value: 25 },
      ],
    },
  },
  {
    id: 23,
    name: "Diesel",
    unit: "1 Liter",
    price: 55,
    change: -1,
    category: "fuel",
    source: sources.localStation,
    image: "/products/diesel.jpg",
    description: "Diesel fuel price at Kabul fuel stations.",
    priceHistory: generatePriceHistory(55, 0.04),
    calculator: {
      baseQuantity: 1,
      displayUnit: "liter",
      step: 1,
      min: 1,
      presets: [
        { label: "5 L", value: 5 },
        { label: "10 L", value: 10 },
        { label: "20 L", value: 20 },
        { label: "30 L", value: 30 },
        { label: "50 L", value: 50 },
      ],
    },
  },
  {
    id: 24,
    name: "Kerosene",
    unit: "1 Liter",
    price: 52,
    change: 1,
    category: "fuel",
    source: sources.localStation,
    image: "/products/kerosene.jpg",
    description: "Kerosene for heating and lighting purposes.",
    priceHistory: generatePriceHistory(52, 0.03),
    calculator: {
      baseQuantity: 1,
      displayUnit: "liter",
      step: 1,
      min: 1,
      presets: [
        { label: "5 L", value: 5 },
        { label: "10 L", value: 10 },
        { label: "20 L", value: 20 },
        { label: "30 L", value: 30 },
        { label: "50 L", value: 50 },
      ],
    },
  },
  {
    id: 25,
    name: "CNG",
    unit: "1 m³",
    price: 45,
    change: -0.5,
    category: "fuel",
    source: sources.localStation,
    image: "/products/cng.jpg",
    description: "Compressed Natural Gas for vehicles.",
    priceHistory: generatePriceHistory(45, 0.02),
    calculator: {
      baseQuantity: 1,
      displayUnit: "m³",
      step: 1,
      min: 1,
      presets: [
        { label: "5 m³", value: 5 },
        { label: "10 m³", value: 10 },
        { label: "20 m³", value: 20 },
        { label: "30 m³", value: 30 },
        { label: "50 m³", value: 50 },
      ],
    },
  },

  // =====================
  // METALS
  // =====================
  {
    id: 26,
    name: "Gold 24K",
    unit: "1 Gram",
    price: 6350,
    change: 120,
    category: "metals",
    source: sources.jewelry,
    image: "/products/gold.jpg",
    description: "24 Karat pure gold price per gram.",
    priceHistory: generatePriceHistory(6350, 0.02),
    calculator: {
      baseQuantity: 1,
      displayUnit: "gram",
      step: 0.5,
      min: 0.5,
      presets: [
        { label: "½ g", value: 0.5 },
        { label: "1 g", value: 1 },
        { label: "2 g", value: 2 },
        { label: "5 g", value: 5 },
        { label: "1 mithqal", value: 4.6 },
        { label: "1 tola", value: 11.66 },
      ],
    },
  },
  {
    id: 27,
    name: "Silver",
    unit: "1 Gram",
    price: 78,
    change: -2,
    category: "metals",
    source: sources.jewelry,
    image: "/products/silver.jpg",
    description: "Pure silver price per gram.",
    priceHistory: generatePriceHistory(78, 0.03),
    calculator: {
      baseQuantity: 1,
      displayUnit: "gram",
      step: 1,
      min: 1,
      presets: [
        { label: "5 g", value: 5 },
        { label: "10 g", value: 10 },
        { label: "20 g", value: 20 },
        { label: "50 g", value: 50 },
        { label: "1 tola", value: 11.66 },
        { label: "5 tola", value: 58.3 },
      ],
    },
  },
  {
    id: 28,
    name: "Copper",
    unit: "1 kg",
    price: 745,
    change: 15,
    category: "metals",
    source: sources.jewelry,
    image: "/products/copper.jpg",
    description: "Copper metal price per kilogram.",
    priceHistory: generatePriceHistory(745, 0.025),
    calculator: {
      baseQuantity: 1,
      displayUnit: "kg",
      step: 0.5,
      min: 0.5,
      presets: [
        { label: "½ kg", value: 0.5 },
        { label: "1 kg", value: 1 },
        { label: "2 kg", value: 2 },
        { label: "5 kg", value: 5 },
        { label: "1 ser", value: 7 },
      ],
    },
  },
  {
    id: 29,
    name: "Iron",
    unit: "1 kg",
    price: 54,
    change: 0,
    category: "metals",
    source: sources.jewelry,
    image: "/products/iron.jpg",
    description: "Iron metal price per kilogram.",
    priceHistory: generatePriceHistory(54, 0.02),
    calculator: {
      baseQuantity: 1,
      displayUnit: "kg",
      step: 1,
      min: 1,
      presets: [
        { label: "1 kg", value: 1 },
        { label: "5 kg", value: 5 },
        { label: "10 kg", value: 10 },
        { label: "1 ser", value: 7 },
        { label: "5 ser", value: 35 },
      ],
    },
  },
  {
    id: 30,
    name: "Aluminum",
    unit: "1 kg",
    price: 198,
    change: -8,
    category: "metals",
    source: sources.jewelry,
    image: "/products/aluminum.jpg",
    description: "Aluminum metal price per kilogram.",
    priceHistory: generatePriceHistory(198, 0.03),
    calculator: {
      baseQuantity: 1,
      displayUnit: "kg",
      step: 1,
      min: 1,
      presets: [
        { label: "1 kg", value: 1 },
        { label: "5 kg", value: 5 },
        { label: "10 kg", value: 10 },
        { label: "1 ser", value: 7 },
        { label: "5 ser", value: 35 },
      ],
    },
  },
];
