// data.js
export const categories = [
  { id: "essentials", name: "Essentials" },
  { id: "phones", name: "Phones" },
  { id: "currencies", name: "Currencies" },
  { id: "fuel", name: "Fuel" },
  { id: "metals", name: "Metals" },
];

export const sources = {
  baghQazi: { id: "bagh-qazi", name: "Bagh Qazi", shortName: "Bagh Qazi" },
  gulbahar: { id: "gulbahar", name: "Gulbahar Center", shortName: "Gulbahar" },
  saraiShahzada: { id: "sarai-shahzada", name: "Sarai Shahzada", shortName: "Sarai Shahzada" },
  localStation: { id: "local-station", name: "Kabul Fuel Stations", shortName: "Kabul Stations" },
  jewelry: { id: "jewelry", name: "Timur Shahi Market", shortName: "Timur Shahi" },
};

export const items = [
  // Essentials
  {
    id: 1,
    name: "Haji Aziz Rice",
    unit: "3.5 kg sack",
    price: 3800,
    change: 5,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/hajiaziz.jpg",
  },
  {
    id: 2,
    name: "Capsole Beans",
    unit: "1 ser (7kg)",
    price: 750,
    change: 0,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/beans.jpg",
  },
  {
    id: 3,
    name: "Sugar",
    unit: "1kg",
    price: 85,
    change: -3,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/sugar.jpg",
  },
  {
    id: 4,
    name: "Flour",
    unit: "1kg",
    price: 65,
    change: -5,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/flour.jpg",
  },
  {
    id: 5,
    name: "Cooking Oil",
    unit: "1L",
    price: 170,
    change: 0,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/oil.jpg",
  },
  {
    id: 6,
    name: "Eggs",
    unit: "30 pack",
    price: 320,
    change: 15,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/eggs.jpg",
  },
  {
    id: 7,
    name: "Milk",
    unit: "1L",
    price: 80,
    change: -2,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/milk.jpg",
  },
  {
    id: 8,
    name: "Black Tea",
    unit: "500g",
    price: 295,
    change: 10,
    category: "essentials",
    source: sources.baghQazi,
    image: "/products/tea.jpg",
  },

  // Phones (used) - prices in AFN
  {
    id: 9,
    name: "iPhone 16 Pro Max",
    unit: "Used",
    price: 145000,
    change: -2000,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/iphone-16-pro-max.jpg",
  },
  {
    id: 10,
    name: "iPhone 15 Pro",
    unit: "Used",
    price: 98000,
    change: -1500,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/iphone-15-pro.jpg",
  },
  {
    id: 11,
    name: "Samsung S24 Ultra",
    unit: "Used",
    price: 112000,
    change: 3000,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/samsung-s24.jpg",
  },
  {
    id: 12,
    name: "Google Pixel 8 Pro",
    unit: "Used",
    price: 78000,
    change: -2500,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/pixel-8.jpg",
  },
  {
    id: 13,
    name: "Xiaomi 14T",
    unit: "Used",
    price: 52000,
    change: 0,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/xiaomi-14t.jpg",
  },
  {
    id: 14,
    name: "Tecno Camon 30",
    unit: "Used",
    price: 28000,
    change: 1500,
    category: "phones",
    source: sources.gulbahar,
    image: "/products/tecno-camon.jpg",
  },

  // Currencies (against AFN)
  {
    id: 15,
    name: "USD",
    unit: "1 USD",
    price: 70.5,
    change: 0.25,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/usd.jpg",
  },
  {
    id: 16,
    name: "EUR",
    unit: "1 EUR",
    price: 76.2,
    change: -0.15,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/eur.jpg",
  },
  {
    id: 17,
    name: "GBP",
    unit: "1 GBP",
    price: 89.4,
    change: 0.35,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/gbp.jpg",
  },
  {
    id: 18,
    name: "AED",
    unit: "1 AED",
    price: 19.2,
    change: -0.05,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/aed.jpg",
  },
  {
    id: 19,
    name: "PKR",
    unit: "1000 PKR",
    price: 253,
    change: 0,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/pkr.jpg",
  },
  {
    id: 20,
    name: "IRR",
    unit: "100,000 IRR",
    price: 167,
    change: -2,
    category: "currencies",
    source: sources.saraiShahzada,
    image: "/products/irr.jpg",
  },

  // Fuel (prices in AFN)
  {
    id: 21,
    name: "Petrol",
    unit: "1 Liter",
    price: 58,
    change: 2,
    category: "fuel",
    source: sources.localStation,
    image: "/products/petrol.jpg",
  },
  {
    id: 22,
    name: "Liquid Gas",
    unit: "1 kg",
    price: 75,
    change: 0,
    category: "fuel",
    source: sources.localStation,
    image: "/products/lpg.jpg",
  },
  {
    id: 23,
    name: "Diesel",
    unit: "1 Liter",
    price: 55,
    change: -1,
    category: "fuel",
    source: sources.localStation,
    image: "/products/diesel.jpg",
  },
  {
    id: 24,
    name: "Kerosene",
    unit: "1 Liter",
    price: 52,
    change: 1,
    category: "fuel",
    source: sources.localStation,
    image: "/products/kerosene.jpg",
  },
  {
    id: 25,
    name: "CNG",
    unit: "1 m³",
    price: 45,
    change: -0.5,
    category: "fuel",
    source: sources.localStation,
    image: "/products/cng.jpg",
  },

  // Metals (prices in AFN)
  {
    id: 26,
    name: "Gold 24K",
    unit: "1 Gram",
    price: 6350,
    change: 120,
    category: "metals",
    source: sources.jewelry,
    image: "/products/gold.jpg",
  },
  {
    id: 27,
    name: "Silver",
    unit: "1 Gram",
    price: 78,
    change: -2,
    category: "metals",
    source: sources.jewelry,
    image: "/products/silver.jpg",
  },
  {
    id: 28,
    name: "Copper",
    unit: "1 kg",
    price: 745,
    change: 15,
    category: "metals",
    source: sources.jewelry,
    image: "/products/copper.jpg",
  },
  {
    id: 29,
    name: "Iron",
    unit: "1 kg",
    price: 54,
    change: 0,
    category: "metals",
    source: sources.jewelry,
    image: "/products/iron.jpg",
  },
  {
    id: 30,
    name: "Aluminum",
    unit: "1 kg",
    price: 198,
    change: -8,
    category: "metals",
    source: sources.jewelry,
    image: "/products/aluminum.jpg",
  },
];